[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs-18_x', 'yarn']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'npm install --production'
]

[phases.build]
cmds = [
  'php artisan config:cache',
  'php artisan route:cache', 
  'php artisan view:cache',
  'npm run build'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'